version: '3.7'

services:
    rabbitmq:
        image: rabbitmq:3.9.12-management-alpine
        container_name: rabbitmq
#         volumes:
#             - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
#             - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
#             - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: pass
        ports:
            - 5672:5672
            - 15672:15672